# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":sta"
    replace: "⭐️ "
  - trigger: ":wor"
    replace: "💼 "
  - trigger: ":hom"
    replace: "🏠 "
  - trigger: ":tim"
    replace: "🕒 "
  - trigger: ":ex"
    replace: "❗️ "
  - trigger: ":mor"
    replace: "🌅 "
  - trigger: ":noon"
    replace: "🏙 "
  - trigger: ":eve"
    replace: "🌇 "
  - trigger: ":nig"
    replace: "🌠 "
  - trigger: ":weekend"
    replace: "🏝 "
  - trigger: ":cof"
    replace: "☕️ "

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
